### ISSUE TITLE
[Feature Request] Make double pages in one direction as a default

### ISSUE THREAD

**Issue by FireNation323** [Jays2Kings/tachiyomiJ2K#1018]
### Why/User Benefit/User Problem
(explain why this feature should be added)
![Screenshot_20211003-230432_TachiyomiJ2K~2](https://user-images.githubusercontent.com/81137631/135771707-acce0716-ef0c-4a69-b3fc-0d03bf941e68.jpg)
![Screenshot_20211003-230449_TachiyomiJ2K~2](https://user-images.githubusercontent.com/81137631/135771712-83587d5f-bfa7-4d9f-989d-d78ec5fc51d0.jpg)

cleary pic 2 looks way better but it is always set to pic 1 whenever i open a manga 
### What/Requirements
(explain how this feature would behave)
add another option in paged below page layout to set either one of them as default

**Comment by Jays2Kings** [comment]
The button exists because its a case by case basis, the default is first 2 pages and thats not going to change.

Sometimes a chapter of a manga has a translator page, sometimes it doesnt. Sometimes a color page sometimes not. This changes far too often between different manga, chapters, and scanlators for a default to make sense
