### ISSUE TITLE
[Feature Request] webtoon landscape aspect ratio

### ISSUE THREAD

**Issue by Fahad1998** [Jays2Kings/tachiyomiJ2K#103]
### Why/User Benefit/User Problem
Image is too large when in webtoon mode and landscape mode in tall smartphone with 19:5:9 aspects ratio. 

### What/Requirements
Do not fill width in tall smartphones use 16:9 aspect ratio and don't fill width. 

Sorry for bad English.

**Comment by joseph619** [comment]
Just change your Scale type, this already exists

https://tachiyomi.org/help/guides/reader/#scale-type

**Comment by Fahad1998** [comment]
Doesn't work in webtoon mode

**Comment by DragoCubed** [comment]
I think a screenshot would be helpful

**Comment by MariuszBielecki288728** [comment]
I think this issue is similar to https://github.com/inorichi/tachiyomi/issues/1498
With wide screen aspect ratio, e.g. 18:9, the problem is that all currently available scale types don't provide comfortable way of reading manga in landscape rotation mode.


**Fit width/stretch** makes image appear to be to much zoomed in (because height:width ratio is really low) and user has to scroll hard back and forth to keep an image of whole panel imagined in his head. Example (black bar at the right side is from notch camera in my phone) 
![fit_width](https://user-images.githubusercontent.com/22575146/80777890-f1ed3080-8b66-11ea-9446-3147175066f4.jpg)

making some margins/blank space (in order to not fill whole screen, something like 30% margin | 60% page | 30% margin, it would look like below).
![with_margins](https://user-images.githubusercontent.com/22575146/80777894-f6b1e480-8b66-11ea-9f90-16cdc92da67f.jpg)



**Fit height/Fit screen** is quite useless in landscape, because image is simply too small.

**Original size** is the best option because it usually doesn't fill whole screen, but the problem is that pages have inconsistent resolution and requires frequent pinching to change zoom.

**Comment by CarlosEsco** [comment]
There is a side padding option in the next release

**Comment by Jays2Kings** [comment]
Added
