### ISSUE TITLE
[Feature Request] "Long Strip" tag should default to Webtoon reading mode instead of locking reading mode to Webtoon

### ISSUE THREAD

**Issue by staticV3** [Jays2Kings/tachiyomiJ2K#1097]
### Why/User Benefit/User Problem
Locking the reading mode to Webtoon with a "Cannot change the reading mode from webtoon. Edit the series type first to change" pop-up notification serves no purpose apart from making the process of changing modes in case of bad tags more tedious by requiring the user to edit the tags first. Then change modes.

### What/Requirements
When Long Strip/Webtoon tags are present, reading mode should automatically be set to Webtoon.
That's all these tags should do. Anything else should be removed from the App, as it only causes problems and serves no purpose.

**Comment by Jays2Kings** [comment]
Not sure why you would want to read something that's in long strip format in a not webtoom format, but this was originally done for those who have been using the since way back and had certain series in the library with the wrong initial reading mode.

It's been over a year since that issue so at this point the locked webtoon mode can probably be removed by now
