### ISSUE TITLE
 switching odd or even page stitching

### ISSUE THREAD

**Issue by LoliconPRO** [Jays2Kings/tachiyomiJ2K#1167]
Combine 2 pages ，The first page of Japanese comics should not spliced
![未标题-1](https://user-images.githubusercontent.com/38858821/154847677-6fcdfea8-8ac4-4812-aff3-aa1dfd27b309.jpg)
，

**Comment by Zazazasu** [comment]
I'd like for this to be added too, for the opposite reason. Some manga don't have cover pages, but tachiyomi ends up displaying page 1 by itself anyway. For example, a manga has 4 pages. It will display 1, 2-3, 4, instead of 1-2, 3-4. If I toggle "Shift one page over" on and off, it will display 1-2, 3-4, but I'd have to do that every chapter.
