### ISSUE TITLE
Fix "Edit Category" Scroll Issue

### ISSUE THREAD

**Issue by w00ogly** [Jays2Kings/tachiyomiJ2K#1433]
### Steps to reproduce

1. Go to Settings -> Open Library -> Edit Categories 
2. Move Categories 
3. Can't switch categories

### Expected behavior

When making and moving categories normally you should be able to put where you want.

### Actual behavior

https://user-images.githubusercontent.com/111436425/194196417-0d379629-5529-4f44-b99e-80869055fdb8.mp4

### TachiyomiJ2K version

1.5.9

### Android version

Android 12

### Device

Galaxy Tab S7

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [ ] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I am reporting an issue exclusive to this fork. I have also checked that is not an issue on the [main version of Tachiyomi](https://github.com/tachiyomiorg/tachiyomi)
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[1.5.9](https://github.com/Jays2Kings/tachiyomiJ2K/releases/latest)**.
- [X] I have updated all installed extensions.
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] I have filled out all of the requested information in this form.

**Comment by Adoridenn** [comment]
I also have this issue.  I reported it to nekos repository 4 months ago and no fix,  seems like this issue is spread across multiple forks of tach. Really hope this gets fixed soon.. I'm using samsung galaxy tab s8 ultra,  android 13. Also happens on phone, one plus n10 5g, and tab s7. In meantime I think temp solution is to find older version where this doesn't happen, (can try to install older versions on emulator on pc until you find one that works) make backup, del lib and app data, uninstall and install older version. Then reorganize your stuff, maybe even make new categories you don't even use now so you don't have to do this again, make backup, install new version and then restore. It's stupid but only way to get around this bug as far as I know, can also try shuffling then around until they are where you want them, since you can still move stuff in the top section until it starts scrolling back to the top. That's what I'm going to have to do, will take forever, like some kind of twisted puzzle lol..

**Comment by ShiroYasha139** [comment]
I'm having the same issue as well. I had restored my backup when I installed the app. Now I wanted to create a new category and put it near the end and I have this issue where moving it down just moves it above. It messed up my category order completely since I accidentally moved other categories too.
