### ISSUE TITLE
[Feature Request] Sortable/Re-Order download queue

### ISSUE THREAD

**Issue by Zenothia** [Jays2Kings/tachiyomiJ2K#15]
Android version: 9
Request: Sortable download queue (Re-order Download queue)

I like the download queue to be Sortable via drag and drop so that I don't have to clear the whole queue when the new one is in.
Edit: I want the sorting based on series or chapter if the series is not possible (priority like in IDM queue).

The reason is simple because I like the new updated chapters (currently reading manga) to be on my top priority among my plan to read chapters.

Example:
I have 100 chapters of plan to read manga that is currently downloading. Then there are 10 new chapters are out from my reading list. I want that 10 new chapters to be able to place on top or can be dragged easily so that I can download them first.
Clearing an re-adding chapters is time consuming especially when you have tons of library updates.

**Comment by de-odex** [comment]
Addon suggestion: a priority system, so numbers can increase priority (if same priority, sort by insertion time) then a "manual sort" priority for manually modified sorts

**Comment by Jays2Kings** [comment]
Added the option to reorder the queue however you choose as of 0.9.4. Adding a priority system seems like too complex a system to manage (for both me as a dev and me as a user). 

In the future I can possibly add an option to reorder the queue based on newest chapters, but that will just be from the download queue page because ordering the downloads when you add a new download would become a nightmare.

**Comment by Jays2Kings** [comment]
And as of 0.9.6 an option to reorder downloads has been added plus more. Since the prioritize system can't be implemented, this will now be marked as done
