### ISSUE TITLE
[Feature Request] Optional Dark snackbar on Dark / Dark Blue theme + Option to remove rounded corners

### ISSUE THREAD

**Issue by Nydid** [Jays2Kings/tachiyomiJ2K#156]
### Why/User Benefit/User Problem
The Dark Snackbar would help with not being blinded by light in a dark environment on an AMOLED display (many of the people I recommended Tachi-j2k to complained about this aswell).
![Screenshot_20200328-230935](https://user-images.githubusercontent.com/30263820/77835379-4f4b2780-714c-11ea-9c26-1ba83dc0c70d.jpg)
![Screenshot_20200328-231425](https://user-images.githubusercontent.com/30263820/77835380-4fe3be00-714c-11ea-9d1f-0067fdf34cfc.jpg)

Also, an option to enable / disable rounded corners, people like me who have sharp user interfaces with rectangle boxes, and other UI elements of the same aesthetics

**J2K  \\/** ![Screenshot_20200328-232637__01](https://user-images.githubusercontent.com/30263820/77835423-b79a0900-714c-11ea-850a-41a1e4f52ace.jpg) (Also, any reason why a color change on certain UI elements like this one? The blurring already brings the element out from the background)
**Stable Tachi  \\/** ![Screenshot_20200328-232711__01](https://user-images.githubusercontent.com/30263820/77835424-b8329f80-714c-11ea-9447-9b46fb5f9847.jpg)

### What/Requirements
Add an option in general (or advanced) where we could hit a switch for Light / Dark Snackbars
Same thing for Rounded / Sharp UI

Thanks for reading!

**Comment by CarlosEsco** [comment]
1.  Reasonable request
2.  Not likely to happen configurable dialog corners is so niche
3.  Personal preference?  This isn't the main app it's not going to match 100%

**Comment by Nydid** [comment]
1. Nothing to add
2. You never know unless you ask
3. This only something I noticed while looking at 2. it's not a request, just something I observed

**Comment by joseph619** [comment]
Snackbar is already dark on AMOLED theme, it's white for Dark theme.

**Comment by Jays2Kings** [comment]
The first point is valid, but that's because it's too bright right now. With the next major version I'm no longer going to manually make the snackbar white since the app will make dark themes have a lighter snackbar (but now it'll be pale gray than a bright white), so the option of customizing it isn't going to happen

The second point won't happen because rounded is the direction android and the app is going anyway and an option to make it sharp is pointless

The third point is something you'd never notice unless you were looking at both apps anyway, it's pointless to be exactly like the original tachi anyway

**Comment by Jays2Kings** [comment]
As of 1.0.0 the snackbar in dark mode isn't a bright now, so this can be closed
