### ISSUE TITLE
Unable to access Library post-1.7.1 update

### ISSUE THREAD

**Issue by madroctos** [Jays2Kings/tachiyomiJ2K#1619]
### Steps to reproduce

1. Updated to 1.7.1
2. Opened the app, default is set to History, waited for history to load
3. When it didn't load checked the library and it was loading
4. Closed the app, Force closed it, cleared the cache both in-app and through android system
5. Reopened and the same thing happened, only this time only the History was showing entries
6. Has not worked for almost an hr

### Expected behavior

What should happen is my library should show up

### Actual behavior

What actually happens is that it doesn't 

### TachiyomiJ2K version

1.7.1

### Android version

13

### Device

Galaxy Note20 Ultra

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I am reporting an issue exclusive to this fork. I have also checked that is not an issue on the [main version of Tachiyomi](https://github.com/tachiyomiorg/tachiyomi)
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[1.7.1](https://github.com/Jays2Kings/tachiyomiJ2K/releases/latest)**.
- [X] I have updated all installed extensions.
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] I have filled out all of the requested information in this form.

**Comment by Jays2Kings** [comment]
Since you can load up recents, try making a backup in settings, clear the app data and then restore that backup to see if it resolved the issue

**Comment by Jays2Kings** [comment]
Try downgrading to 1.6.6 I guess? It seems like Samsung devices having some database issues

**Comment by fetty651** [comment]
I uninstalled, still didn't work. I'm on a Pixel 7.

**Comment by Jays2Kings** [comment]
@fetty651 post crash logs from advanced settings

**Comment by fetty651** [comment]
For 1.6.6 or 1.7.1?

**Comment by Jays2Kings** [comment]
1.7.1 can you try upgrading again?

**Comment by fetty651** [comment]
Here you go. I updated it and after it crashed, I dumped the logs. If there's a different way to do it let me know.

App version: 1.7.1 (standard, b5a0316a6, 106, 2023-09-28T00:41Z)
Android version: 13 (SDK 33)
Android build ID: TQ3A.230805.001
Device brand: google
Device manufacturer: Google
Device name: cheetah
Device model: Pixel 7 Pro
Device product name: cheetah

--------- beginning of main
09-28 16:09:02.649 18897 18897 E e.tachiyomi.j2k: Not starting debugger since process cannot load the jdwp agent.
09-28 16:09:03.283 18897 18897 E SQLiteLog: (283) recovered 764 frames from WAL file /data/data/eu.kanade.tachiyomi.j2k/databases/tachiyomi.db-wal
09-28 16:09:03.297 18897 19064 E SQLiteLog: (284) automatic index on C(manga_id)
09-28 16:09:03.297 18897 19064 E SQLiteLog: (284) automatic index on R(manga_id)
09-28 16:09:03.297 18897 19064 E SQLiteLog: (284) automatic index on B(manga_id)
09-28 16:09:20.320 18897 19061 E SQLiteLog: (284) automatic index on mangas(_id)
09-28 16:09:36.697 19349 19349 E e.tachiyomi.j2k: Not starting debugger since process cannot load the jdwp agent.
09-28 16:09:36.906 19349 19484 E chromium: [0928/160936.906276:ERROR:variations_seed_loader.cc(69)] Failed to open file for reading. Errno: 2
09-28 16:09:39.243 19349 19349 E RippleDrawable: The RippleDrawable.STYLE_PATTERNED animation is not supported for a non-hardware accelerated Canvas. Skipping animation.
09-28 16:09:39.247 19349 19430 E FrameEvents: updateAcquireFence: Did not find frame.
09-28 16:09:39.252 19349 19571 E SQLiteLog: (284) automatic index on mangas(_id)
09-28 16:09:41.298 19349 19430 E FrameEvents: updateAcquireFence: Did not find frame.
09-28 16:09:48.689 19349 19547 E SQLiteLog: (284) automatic index on C(manga_id)
09-28 16:09:48.689 19349 19547 E SQLiteLog: (284) automatic index on R(manga_id)
09-28 16:09:48.689 19349 19547 E SQLiteLog: (284) automatic index on B(manga_id)
09-28 16:09:54.099 19349 19349 E RippleDrawable: The RippleDrawable.STYLE_PATTERNED animation is not supported for a non-hardware accelerated Canvas. Skipping animation.
09-28 16:09:54.102 19349 19430 E FrameEvents: updateAcquireFence: Did not find frame.
09-28 16:09:55.293 19349 19349 E RippleDrawable: The RippleDrawable.STYLE_PATTERNED animation is not supported for a non-hardware accelerated Canvas. Skipping animation.
09-28 16:09:55.296 19349 19430 E FrameEvents: updateAcquireFence: Did not find frame.
09-28 16:09:56.426 19349 19349 E RippleDrawable: The RippleDrawable.STYLE_PATTERNED animation is not supported for a non-hardware accelerated Canvas. Skipping animation.
09-28 16:09:56.430 19349 19430 E FrameEvents: updateAcquireFence: Did not find frame.
09-28 16:09:57.092 19349 19349 E RippleDrawable: The RippleDrawable.STYLE_PATTERNED animation is not supported for a non-hardware accelerated Canvas. Skipping animation.
09-28 16:09:57.097 19349 19430 E FrameEvents: updateAcquireFence: Did not find frame.
09-28 16:09:57.676 19349 19349 E RippleDrawable: The RippleDrawable.STYLE_PATTERNED animation is not supported for a non-hardware accelerated Canvas. Skipping animation.
09-28 16:09:57.680 19349 19430 E FrameEvents: updateAcquireFence: Did not find frame.
09-28 16:09:58.866 19349 19349 E RippleDrawable: The RippleDrawable.STYLE_PATTERNED animation is not supported for a non-hardware accelerated Canvas. Skipping animation.
09-28 16:09:58.869 19349 19430 E FrameEvents: updateAcquireFence: Did not find frame.
09-28 16:10:02.276 19349 19349 E RippleDrawable: The RippleDrawable.STYLE_PATTERNED animation is not supported for a non-hardware accelerated Canvas. Skipping animation.
09-28 16:10:02.280 19349 19430 E FrameEvents: updateAcquireFence: Did not find frame.
09-28 16:10:18.742 19739 19739 E e.tachiyomi.j2k: Not starting debugger since process cannot load the jdwp agent.
09-28 16:10:18.957 19739 19803 E chromium: [0928/161018.956977:ERROR:variations_seed_loader.cc(69)] Failed to open file for reading. Errno: 2
09-28 16:10:19.180 19739 19793 E SQLiteLog: (283) recovered 12 frames from WAL file /data/data/eu.kanade.tachiyomi.j2k/databases/tachiyomi.db-wal

**Comment by Jays2Kings** [comment]
@fetty651 send me the backup file you have since I can't seem to reproduce, you can add me on discord too if you dont want to send it here

**Comment by GMak9** [comment]
I'm having the same problem loading the library, after I upgraded straight from version 1.6.6 to 1.7.1.

**Comment by zer0p1us** [comment]
Same issue on 1.7.1 on a Samsung, same on tried 1.7.2-b01, works fine on 1.6.6, it takes a good 45ish seconds to load anything, admittedly it takes some 5-6 secs on 1.6.6 simply as a virtue of large library

**Comment by fetty651** [comment]
I have a large library as well. Cutting it in half fixed it, but it still loads slow.

**Comment by fetty651** [comment]
Will this be updated in the next patch? Or is it already fixed with this one? I'm not too familiar with this stuff, so I'm not sure.

**Comment by Jays2Kings** [comment]
The next update
