### ISSUE TITLE
[Beta] [UI Improvement] Reader Settings Sheet

### ISSUE THREAD

**Issue by Sai-P** [Jays2Kings/tachiyomiJ2K#188]
### Why/User Benefit/User Problem
Replacing the bottom arrow with a Material Design 2.0 style pill pull-tab makes the design of the bottom sheet look more consistent and elegant, putting it in-line with the rest of the app UI.

The current implementation is a tad bit out-of-place and a bit of an eyesore imo.

#### Current
![before](https://user-images.githubusercontent.com/18060651/79090741-af2efa00-7d18-11ea-8b27-fbb6b9bce167.jpg)

#### After
![after](https://user-images.githubusercontent.com/18060651/79090747-b229ea80-7d18-11ea-8ca9-28ee4837777d.jpg)

**Comment by Jays2Kings** [comment]
The pill only makes sense if there's something to scroll up for (this is fully expanded so it doesn't make sense here)

Still it should be an X instead of that and only showing when sheet takes up the fullscreen, but I'm still closing this issue so people dont the idea to make feature requests for a beta
