### ISSUE TITLE
[Feature Request] One tap global search

### ISSUE THREAD

**Issue by reddeimon** [Jays2Kings/tachiyomiJ2K#252]
### Why/User Benefit/User Problem
TachiJ2K right now in order to global search a manga name you found from a source, you have to Add to Library -> Migrate manga -> Select target sources -> Data to include in migration -> Search manually. The feature I propose will do just that by simply clicking the manga title. This is useful to compare sources or search in long name without typing.

### What/Requirements
It's basically the same as clicking the manga title like the original Tachiyomi, in fact I don't mind if you add it back without changing anything. In the current TachiJ2K if you pick a source after Search manually you can't go back to pick another source but instead keep clicking Search manually again. It will ask you if you want to stop migration if you do want to go back. This feature basically just a global search not a migration.

**Comment by CarlosEsco** [comment]
Your alternative is possibly the longest way. Assuming you are in a source and you want to search others.  Long press title back til you are global search then paste into search.  Long pressing a title in the info screen copies it

**Comment by reddeimon** [comment]
Not really an alternative, it's just an old feature I love to have again. I tried what you told, long press -> back -> browse -> paste title. I think the old feature clicking the title is faster. At least can we have enable/ disable option for this feature?

**Comment by CarlosEsco** [comment]
its definitely an alternative to adding the manga and then migrating it.

**Comment by clombion** [comment]
I'm not sure I understand Carlos' answer, but here are my scenarios:

**Scenario 1**
I removed an obsolete and discovered afterwards that a few titles were linked to the extention. Their source now reads as a bunch of numbers (19993739837383 or something like that). Is mass migration possible in this case? I was able to find the titles that had this bug by searching "1" (as the search includes the source name, and there was always a 1 among the numbers). Then for each title, I had to
1. Open the manga overview page from the library
2. Long press to copy the tile
3. Go back to main screen
4. Switch to source
5. Tap on search icon
6. Paste title
7. Launch search
8. Find alternative source and save it
9. Go back to main screen
10. Switch to library
11. Launch search again to find other bugged title

If we were along to launch a source search from a tap on a manga title the flow would be:
1.  Open the manga overview page from the library
2. Tap the manga title to launch source search with the title 
3. Find alternative source and save it
4. Quickly tap "back" twice to be back in the library screen
5. Launch search again to find other bugged title

**Scenario 2**
I find that a manga hasn't been updated in a long time. I'm not sure if it's because of the source or because there was simply no update. So I want to compare sources. With the "tap title for source search" function it's a few steps:
1. Tap on manga title from overview page
2. Check other sources
3. If another source is more up to date, add it
4. Tap back button twice to go back to manga overview
5. Remove from library

**Scenario 3**
I'm reading a manga and I'm wondering if there are doujins/alt stories. Again, the "tap title for source search" becomes a great shortcut as doujin/alt stories will generally use the same name.

**Comment by CarlosEsco** [comment]
No worries it should be addressed soon. My scenario was when people were browsing a source click into and want to read but the source has almost no chapters
