### ISSUE TITLE
[Feature Request] Re-Migrate to Same Extension

### ISSUE THREAD

**Issue by iAmPhilo** [Jays2Kings/tachiyomiJ2K#40]
### Why/User Benefit/User Problem
Sometime some Manga get unbookmarked from the main source (Mangakakalot) even though it is still in your Library. You can find this out by looking through Catalogue or searching the Manga. It will be like a new Manga, all chapters unread and not bookmarked. Bookmarking it again will duplicate in your Library. Also the old bookmarked one stops receiving chapter update.

The benefit of re-migrating to the same source would save user from migrating to another extension then back to the old one.

### What/Requirements
Enabling migration to same extension/source.

**Comment by Jays2Kings** [comment]
Since this is such a specific issue for certain source, instead you can migrate the old one, uses the 3 dots and search manually, the new manga in the source should show up there, and you can migrate on the same source that way.

Having the option to search the same source only leads to having the same manga show up again, which is likely to happen if you're migrating from different sources from the same time

**Comment by iAmPhilo** [comment]
Regarding your last point, the same source won't show up, it will be a new one unbookmarked. Which is what I need to transfer it over to that one. Reason why I know is that it worked using your old migration system before moving to the new one. (The Manga picture wasn't greyed out, it was full colour, showing like a not bookmarked manga).

**Comment by Jays2Kings** [comment]
The new one has a search manually option and you can migrate to the same source that way.
![Screenshot_20200108-084538](https://user-images.githubusercontent.com/8617760/71997986-a4ce0300-31f3-11ea-89a7-4999b3d65e5f.png)

You can also still use the old source migration by going to the source migration screen and tapping "select" instead of auto

**Comment by iAmPhilo** [comment]
Yeah the manual one works great but I have like 500 Manga and at least more than 50 have been unbookmarked. So it would take forever.

Regarding the old migration, I can't seem to find that option? There is no auto or select button when I go to that screen.

**Comment by iAmPhilo** [comment]
Nevermind I found the select and auto screen. But having to do it manually for each one would take forever :P - sorry about this, but is there any reason why we can't use the same source to find the same manga? I have a feeling either it's an extension problem or Mangakakalot changed something in the URL or text.

**Comment by Jays2Kings** [comment]
It doesn't happen that often and at the same time though correct? Adding that just makes the auto migration slower, and leads to getting the same manga on all sources but mangakakalot. To hinder the codebase and user experience for auto migration because of one source behaves like this is kind of unreasonable.

**Comment by iAmPhilo** [comment]
It did do it on the older version before the new migration came out. But I didn't realize how many I was missing till recently.

Fair, I thought you could just implement it to think of it as a separate source when searching instead of showing no found or n/a using the same source.

**Comment by CarlosEsco** [comment]
even as a separate source the use case is so specific.   it would only work if a source changed their urls
