### ISSUE TITLE
[Bug] page slider skips to next chapter

### ISSUE THREAD

**Issue by vongdong** [Jays2Kings/tachiyomiJ2K#461]
### Device information
* Tachiyomi version: 1.0.7
* Android phone & version: Galaxy Tab S6 android 10

## Steps to reproduce
1. Open manga
2. use page slider at bottom

### Expected behavior
slider should only be showing current chapter pages

### Actual behavior
goes to next chapter 

### Other details
I've notivced it happens when using the slider a bit fast. It goes to the next chapter seemlessly so I don't notice until I don't understand what's happening in the manga.

**Comment by geominorai** [comment]
I think you are actually clicking the part of the panel _under_ slider.

I have Android gesture navigation enabled so the area where the navigation bar soft keys normally would be is replaced with a large vertical gap.  This gap is actually clickable, and it does not jump to the next chapter but whatever manga chapter at the top is currently visible in the chapter list slide-up menu that's supposed to be hidden.

So the real bug is a hidden panel is still registering clicks.

**Comment by vongdong** [comment]
> 
> 
> I think you are actually clicking the part of the panel _under_ the slider.
> 
> I have Android gesture navigation enabled so the area where the navigation bar soft keys normally would be is replaced with a large vertical gap. This gap is actually clickable, and it does not jump to the next chapter but whatever chapter at the top of the currently visible section of the chapter list slide-up menu that's supposed to be hidden. So for me, clicking on it actually jumps from 1 -> 4 -> 7 etc.
> 
> So the real bug is a hidden panel is still registering clicks.

Nah, that's not what's happening with me. It goes to the next chapter seamlessly. Say I'm skimming through a chapter to 3/4 of it, it changes to the last 1/4 of the next chapter.

**Comment by joseph619** [comment]
@Jays2Kings user doesn't use J2K anymore, can close
