### ISSUE TITLE
[Feature Request] Show content in cutout area option

### ISSUE THREAD

**Issue by ADMOrange0115** [Jays2Kings/tachiyomiJ2K#517]
Good day devs, is it possible for the J2K fork to also have the option to toggle "Show content in cutout area option"? for us user to freely select if we want a cutout experience while reading or not. Thank you for the awesome UI for the J2K fork, it's much more up to date looking in appearance. I hope the the cutout option will come on the next update.

**Comment by XxJibril** [comment]
what do you mean by cutout area ?

**Comment by LewAndrade** [comment]
I was about to open an issue requesting exactly this...
Any updates about this one feature???

**Comment by CarlosEsco** [comment]
This should already work in webtoon mode,  why would you want this in paged view?  wouldnt just cut into the image and prevent reading correctly

**Comment by LewAndrade** [comment]
Idk if my use case is weird or what,,, actually i read comics in webtoon mode using landscape layout, and the camera notch is actually small, so it doesn't disrupt the content enough to bother me. 
I just wanted to have the option to display the content ignoring the notch, as I do in the stable tachiyomi fork.

**Comment by telumletiferum** [comment]
Is there any progress on this. I think this feature would be pretty nice since I always read manga like that in Tachiyomi.

**Comment by bubin7766** [comment]
I noticed that this issue was fixed for landscape but it's functionality never applied to portrait mode
Is this an oversight or at the time was this the only solution available? 
If possible it'd be nice to toggle off the portrait cutout area in addition to landscape as it is now
Sorry for messaging on an old thread, it just felt like it was relevant here instead of opening a new one
