### ISSUE TITLE
[Feature Request] Number of Chapters in Search

### ISSUE THREAD

**Issue by Xeiniac** [Jays2Kings/tachiyomiJ2K#57]
### Why/User Benefit/User Problem
They can see how many chapters the manga on the source has instead of clicking each of them one by one and maybe the latest chapter number under it too
### What/Requirements
Show's a box top left with the number of chapters and latest chapter below the image like how it shows in auto migrate but without the source name.
![Screenshot_Tachiyomi_20200113-195300](https://user-images.githubusercontent.com/25398298/72263266-8d04dd80-363e-11ea-8624-2bf24c8ade93.png)

**Comment by CarlosEsco** [comment]
This is not really feasible.  No source that i know of provides the chapters count in a browse view.
You would end up either ddosing the website everytime you searched, or getting banned by the source.  If you rate limited it.  It would take forever for chapter counts to show.

right now there is 
1 http request to get all the manga
1 http request per manga to get the cover 

to get chapter lists you are adding an extra http request per a manga
so 25 manga instead of 26 requests becomes 51 request so on and so forth.

**Comment by Xeiniac** [comment]
Oh alright that makes sense, thanks for the reply 😃

**Comment by Jays2Kings** [comment]
That still has the same issue, you would get banned or rate limited by doing that. Migration does it because it checks for a single manga, where search would absolutely cause issues.

This won't be added
