### ISSUE TITLE
[Bug] Can't change viewer after automatic webtoon

### ISSUE THREAD

**Issue by Kycklingris** [Jays2Kings/tachiyomiJ2K#649]
### Device information
* Tachiyomi version: 1.0.10
* Android phone & version:  Mi 9, android 10

## Steps to reproduce
1. Read "webtoon" (ain't gonna say what I was actually reading but it wasn't a webtoon)
2. Try to change reader from webtoon
3. Notice it changes back immediately

### Expected behavior
Well, I mean, I just realised, it may be intended, but If so, it's a large problem when it gets it wrong. So, it should only auto change once?

### Actual behavior
It stays on webtoon regardless

**Comment by CarlosEsco** [comment]
if its wrong, its source issue tbf.  You can edit the manga in app and remove the webtoon/longstrip tag from it.

**Comment by have-a-boy** [comment]
I have the same issue trying to read "World's Connection" from the Webtoons.com source. There's no Webtoon/Longstrip tag to remove. Is this something that should be reported to the extensions issue tracker or is this specific to the j2k fork?

I'm sure that at least the UI could be improved, since it currently accepts user input to change the view mode, but resets it after closing the menu. Is it possible to only use source info to provide a default setting that can be overridden by a choice from the user?
