### ISSUE TITLE
[Feature Request] Option to put local manga cache in SD Card

### ISSUE THREAD

**Issue by allandck123** [Jays2Kings/tachiyomiJ2K#744]
App version: 1.0.13

Android version: 9

Issue/Request: The app creates new folder containing local manga covers in internal storage, plea

Steps to reproduce:
 1. Local manga located in SD Card
 2. Browse local manga in app

Other details: 
So, I stored my local manga in SD Card. When I opened them in app, the app always make a new folder in internal storage containing each titles and their cover wasting space in my internal storage, and they also show up in gallery. Is there any way to disable this?

**Comment by Plut0nio** [comment]
I'm having issues with this in 1.7.4. My local manga is stored in /storage/[SD card]/Tachiyomi/local/ (there's currently no way to change Tachiyomi J2K's local manga storage location to, for example, /storage/[SD card]/Tachiyomi J2K/local/), but I have to keep the covers in /storage/emulated/0/Tachiyomi/local/ for all the covers to work. Trying to set a cover manually results in the cover being saved to /storage/emulated/0/TachiyomiJ2K/local/ (the dir is created if it doesn't already exist).

/storage/emulated/0/ is my internal storage rather than my SD card, btw.
