### ISSUE TITLE
[Feature Request] The screen can be fully covered under e-ink 

### ISSUE THREAD

**Issue by hanxin1997** [Jays2Kings/tachiyomiJ2K#935]
### Why/User Benefit/User Problem
More convenient to use

### What/Requirements
On the basis of filling the screen, remove the background on both sides.
Currently using "fitscreen" mode is not good
This one uses {crop borders} so the bottom is covered
![QQ图片](https://user-images.githubusercontent.com/58620096/126037842-50fca0d0-0c34-4a3e-9a62-2227f7ca5ab5.jpg)

**Comment by Jays2Kings** [comment]
You can use "stretch" instead of "fit screen" then

**Comment by hanxin1997** [comment]
> 您可以使用“拉伸”而不是“适合屏幕”然后



> You can use "stretch" instead of "fit screen" then

I have used it, but the display below is not complete. You need to pull it down to see it, but this is fatal to e-ink.
![QQ图片1](https://user-images.githubusercontent.com/58620096/126054320-0b99ff85-45fe-4f5a-979b-10e9990145de.jpg)

**Comment by hanxin1997** [comment]
> You can use "stretch" instead of "fit screen" then

The left and right are all displayed, but the bottom is not fully displayed

**Comment by Jays2Kings** [comment]
Nothing can be done then, the image does not fit your device size, so either you will have part of it off screen, or you will see part of the border.

The only other option is to expand the image to fill the screen but then this will make the image disproportional and will make art and text stretched out and look bad, so this won't happen

I'm closing this since that seems to be what you're asking, and that won't be coming
